services:
  api:
    build: .
    container_name: farmengine-api
    ports:
      - "8000:8000"
    environment:
      - MONGO_URL=mongodb://host.docker.internal:27017
    privileged: true # Necesario para que psutil acceda al hardware real