version: '3.8'
services:
  frontend:
    container_name: react-frontend
    build:
      context: ./frontend
    ports:
      - "80:80"  # En lugar de "3000:80"
    environment:
      - REACT_APP_API_URL=http://node-api:5000
